apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-taker
  namespace: sre-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-taker
  template:
    metadata:
      labels:
        app: note-taker
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: note-taker
          image: notsuoholi/note-taker:latest
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
