---
apiVersion: v1
kind: Service
metadata:
  name: note-taker
  namespace: sre-challenge
spec:
  selector:
    app: note-taker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
