apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: sre-challenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'note-taker'
        static_configs:
          - targets: ['note-taker:3000']
